if(NOT DEFINED TOOL OR NOT DEFINED WORK)
    message(FATAL_ERROR "TOOL and WORK are required")
endif()
file(MAKE_DIRECTORY "${WORK}")
string(ASCII 65 66 67 68 69 70 PIXELS)
file(WRITE "${WORK}/source.ppm" "P6\n2 1\n255\n${PIXELS}")
execute_process(COMMAND "${TOOL}" encode "${WORK}/source.ppm" "${WORK}/image.wimf"
                RESULT_VARIABLE ENCODE_RESULT)
if(NOT ENCODE_RESULT EQUAL 0)
    message(FATAL_ERROR "native encode failed: ${ENCODE_RESULT}")
endif()
execute_process(COMMAND "${TOOL}" decode "${WORK}/image.wimf" "${WORK}/decoded.ppm"
                RESULT_VARIABLE DECODE_RESULT)
if(NOT DECODE_RESULT EQUAL 0)
    message(FATAL_ERROR "native decode failed: ${DECODE_RESULT}")
endif()
file(READ "${WORK}/source.ppm" SOURCE_HEX HEX)
file(READ "${WORK}/decoded.ppm" DECODED_HEX HEX)
string(LENGTH "${SOURCE_HEX}" SOURCE_HEX_LENGTH)
string(LENGTH "${DECODED_HEX}" DECODED_HEX_LENGTH)
math(EXPR SOURCE_RASTER_OFFSET "${SOURCE_HEX_LENGTH} - 12")
math(EXPR DECODED_RASTER_OFFSET "${DECODED_HEX_LENGTH} - 12")
string(SUBSTRING "${SOURCE_HEX}" ${SOURCE_RASTER_OFFSET} 12 SOURCE_RASTER)
string(SUBSTRING "${DECODED_HEX}" ${DECODED_RASTER_OFFSET} 12 DECODED_RASTER)
if(NOT SOURCE_RASTER STREQUAL DECODED_RASTER)
    message(FATAL_ERROR "native PPM round trip changed raster bytes")
endif()
