if(NOT DEFINED TOOL OR NOT DEFINED WORK)
    message(FATAL_ERROR "TOOL and WORK are required")
endif()
file(MAKE_DIRECTORY "${WORK}")
string(ASCII 1 2 3 4 5 6 PIXELS)
file(WRITE "${WORK}/source.ppm" "P6\n2 1\n255\n${PIXELS}")
execute_process(COMMAND "${TOOL}" encode "${WORK}/source.ppm" "${WORK}/image.wimf"
                RESULT_VARIABLE ENCODE_RESULT)
if(NOT ENCODE_RESULT EQUAL 0)
    message(FATAL_ERROR "native encode failed: ${ENCODE_RESULT}")
endif()
execute_process(COMMAND "${TOOL}" decode "${WORK}/image.wimf" "${WORK}/decoded.ppm"
                RESULT_VARIABLE DECODE_RESULT)
if(NOT DECODE_RESULT EQUAL 0)
    message(FATAL_ERROR "native decode failed: ${DECODE_RESULT}")
endif()
file(SHA256 "${WORK}/source.ppm" SOURCE_HASH)
file(SHA256 "${WORK}/decoded.ppm" DECODED_HASH)
if(NOT SOURCE_HASH STREQUAL DECODED_HASH)
    message(FATAL_ERROR "native PPM round trip was not exact")
endif()
